### ISSUE TITLE
improve ocean.js code, eliminate code duplication, etc.

### ISSUE THREAD

**Issue by ssallam** [oceanprotocol/ocean.js#637] opened 2021-03-02 13:47 UTC

**Comment by kremalicious** [comment] 2021-03-02 13:51
Please define what needs to be done to close this issue. In this case a good measure would be for CodeClimate metrics:

- Maintainability: A
- Coverage >80%

**Comment by kremalicious** [comment] 2021-03-03 01:31
duplicate of #374

**Closed by kremalicious** 2021-03-03 01:31 UTC
