### ISSUE TITLE
Create minimum base gas fee

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/ocean.js#1661] opened 2022-12-06 12:52 UTC
In situations where gas prices are exceptionally low the gas estimates can lead to a "transaction underpriced" error

### Proposed solution
- A simple solution would be to have a minimum gas base price, 3 gwei should be enough.

**Comment by AnaLoznianu** [comment] 2022-12-20 11:30
Duplicate of #1670

**Closed by AnaLoznianu** 2022-12-20 11:30 UTC
Labels: Type: Enhancement
